### PR TITLE
[Preview] UI tweakings and towards "maintainer queue" features

### PR DESCRIPTION
**Pull request by famz**
For UI preview only. Sorry about the giant big commit, please just git fetch and run.

### CODE REVIEW

**Comment by bonzini** [comment]
BTW, I thought that a good place for the dropdown would be on top, between the search bar and the login button. It could have two parts like

    [ QEMU v ]
    <Quick searches>
    Series without replies
    Merged series
    ----------------------------------
    <Patch queues>
    View queues
    Some other command

**Comment by famz** [comment]
Yeah. I think the bar can also hold the new `<h2>` line to be more compact on headings, what do you think?

**Comment by famz** [comment]
With those, I think the breadcrumb can go way too.

**Comment by bonzini** [comment]
I don't know, I guess it takes some experiments. Personally I tend to have a lot of tabs so I am okay with a little wasted space on the top.

There are several good ideas in this patch, it just takes some time to get them right. On my side I have also merged all the really low-hanging fruit, at some point everything becomes a matter of taste.

**Pull request closed without merging**
